name: server
description: A simple command-line application.
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  socket_io: ^1.0.1
  rikulo_commons: 5.2.0+1
  common:
    path: ../common
dev_dependencies:
  pedantic: ^1.11.1  