name: app_client
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  common:
    path: ../common
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  rx_notifier: ^1.1.0
  socket_io_client: ^1.0.2
  validatorless: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/chat.png
    - assets/background.jpg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/chat.png"